

remote_theme: pmarsceill/just-the-docs

title: CGIAR in Bangladesh


logo: "/assets/images/CGIAR-logo.svg.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


callouts:
  note:
    title: 
    color: green
    opacity: 0.2

# Footer content
footer_content: "Standing Panel on Impact Assessment"

# Footer last edited timestamp
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/asjadnaqvi/DiD" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Change to dark mode here: color_scheme: dark

permalink: pretty
exclude: ["README.md", "Gemfile"]
include: ["docs"]


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "<span style='font-size: 1.08rem; font-weight: 300;'>Innovations Dashboard</span>":
    - "https://isabellarmonteiro.github.io/bd_dashboard/dashboard.html" 

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


nav_sort: case_sensitive # Capital letters sorted before lowercase


# Enable or disable the site search
# Supports true (default) or false
search_enabled: false
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Plug-ins
plugins:
  - jekyll-seo-tag



compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all



usemathjax: true

compress_html:
  blanklines: true # needed to render Mathjax correctly

#layout: default
#title: UI Components
#nav_order: 2
#has_children: true
#has_toc: false


mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

comment-post: https://docs.google.com/forms/d/e/1FAIpQLSeebWfidKoUqHURrP2T7KBMZImBIRlG5MYuuMdDG0SFo-SMVg
comment-read: https://docs.google.com/spreadsheets/d/1Hz_3GQ6BjzOAQeDDhEH8Djq96i_L2tum4KobptSxPq0
comment-post-fields: [ entry.81728054, entry.975896492, entry.134535856]
